# Generated by Django 4.0.3 on 2022-03-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
